### ISSUE TITLE
ModuleNotFoundError: No module named 'causallib.contrib.hemm'

### ISSUE THREAD

**Issue by Mawul4j** [IBM/causallib#11]
Having this error while running this line in hemm_demo
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-027f1a147ace> in <module>
----> 1 from causallib.contrib.hemm.gen_synthetic_data import gen_montecarlo
      2 
      3 syn_data = gen_montecarlo(5000, 2, 100)

ModuleNotFoundError: No module named 'causallib.contrib.hemm'

Any help is appreciated.

**Comment by ehudkr** [comment]
We've yet to release a new version of causallib since the addition of HEMM. Therefore, it is not yet available when installing the package through PyPI (`pip install causallib`).
However, it should be available if you'll use `pip` to install the version currently found in this repository's `master` branch:
```bash
pip install https://github.com/IBM/causallib/archive/master.zip
```

Thanks for bringing this up and sorry for the inconvenience. Please let me know if the problem persists.

**Comment by Mawul4j** [comment]
Still does not work, same error message.
