### ISSUE TITLE
Misstatement  in Standardization example

### ISSUE THREAD

**Issue by bantucaravan** [IBM/causallib#6]
In the text after cell 7, the example describes the model as a Logistic Regression model, whereas I believe the model used in the sklearn LinearRegression() model. 

Source:
https://github.com/IBM/causallib/blob/master/examples/standardization.ipynb

**Comment by ehudkr** [comment]
Yep, that's a typo right there, good catch, we'll fix that. Many thanks!

**Comment by ehudkr** [comment]
Thanks again for raising this issue. The inaccuracy was corrected in commit https://github.com/IBM/causallib/commit/de64cf65d0e2fa1cc5a12d2cc847c970fc43a717, and is still located between code-cells 7 and 8 in [Standardization.ipnyb](https://github.com/IBM/causallib/blob/de64cf65d0e2fa1cc5a12d2cc847c970fc43a717/examples/standardization.ipynb).

I believe that solves it. If you think differently, please let me know. Otherwise I think this issue can be closed.
